<?php declare(strict_types=1);
/**
 * Copyright © W. Poortman - Magewire 2021-present.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getData('viewModel');
?>
<script>
    require(['Magewirephp_MagewireRequireJs/js/magewire'], function (magewire) {
        magewire({
            "app_url": "<?= $escaper->escapeUrl($magewireScripts->getApplicationUrl()) ?>",
            "app_debug": <?= $escaper->escapeJs($magewireScripts->isDeveloperMode() ? 'true' : 'false') ?>
        });
    });
</script>

